name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 2 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to GitHub Pages
      id: gradle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish --scan "-PbintrayUsername=${{ secrets.BINTRAY_USER }}" "-PbintrayPassword=${{ secrets.BINTRAY_KEY }}" "-PdocsNokeeDevAccessKey=${{ secrets.AWS_ACCESS_KEY }}" "-PdocsNokeeDevSecretKey=${{ secrets.AWS_SECRET_KEY }}" "-PpublishToGitHubPagesUsername=nokeedevbot" "-PpublishToGitHubPagesPassword=${{ secrets.GITHUB_TOKEN }}"
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
