name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 2 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to GitHub Pages
      id: gradle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish --scan
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
      env:
        GITHUB_KEY: nokeedevbot
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
